spark.master                     spark://spark-master:7077
spark.driver.host                app
spark.driver.bindAddress         0.0.0.0
spark.driver.port                39000
spark.blockManager.port          39001
spark.sql.session.timeZone       UTC
spark.sql.parquet.compression.codec snappy
spark.ui.showConsoleProgress     true
